# Generated by Django 5.2.5 on 2025-11-09 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='recipes/')),
                ('recipe_text', models.TextField()),
                ('meal_time', models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner')], max_length=10)),
                ('food_type', models.CharField(choices=[('Beverage', 'Beverage'), ('Main Course', 'Main Course'), ('Side', 'Side')], max_length=20)),
                ('pacifies', models.CharField(blank=True, max_length=50)),
                ('aggravates', models.CharField(blank=True, max_length=50)),
                ('specific_conditions', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
